# Generated by Django 4.2.7 on 2024-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='notification_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='notification_status',
            field=models.IntegerField(default=0),
        ),
    ]
